Repository AY2021S1-CS2103T-T10-3/tp, pull requests merged in 2020-10, with the labels that each got.

#38 Refactor model and commands for Ingredient class
  src/main/java/chopchop/commons/core/Messages.java
  src/main/java/chopchop/logic/commands/FindIngredientCommand.java
  src/main/java/chopchop/model/Model.java
  src/main/java/chopchop/model/ModelManager.java
  src/main/java/chopchop/model/ingredient/IngredientBook.java
  src/main/java/chopchop/model/recipe/RecipeBook.java
  src/test/java/chopchop/logic/commands/AddIngredientCommandIntTest.java
  src/test/java/chopchop/logic/commands/AddIngredientCommandTest.java
  src/test/java/chopchop/logic/commands/CommandTestUtil.java
  src/test/java/chopchop/logic/commands/DeleteIngredientCommandTest.java
  src/test/java/chopchop/logic/commands/FilterIngredientCommandTest.java
  src/test/java/chopchop/logic/commands/FindIngredientCommandTest.java
  src/test/java/chopchop/logic/commands/ListExpiringIngredientCommandTest.java
  src/test/java/chopchop/logic/commands/ListIngredientCommandTest.java
  src/test/java/chopchop/model/ModelStub.java
Labels: priority.High

#86 Fix bug
  src/main/java/chopchop/logic/parser/commands/AddCommandParser.java
Labels: type.Bug

#79 Purge AB3 references from everything except the DG
  README.md
  docs/DevOps.md
  docs/SettingUp.md
  docs/Testing.md
  docs/index.md
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
Labels: documentation

#91 Update UG
  docs/UserGuide.md
  docs/index.md
Labels: documentation

#106 Update DG More
  docs/DeveloperGuide.md
  docs/Gemfile.lock
Labels: documentation

#174 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
Labels: documentation

#173 Update UG
  docs/UserGuide.md
  src/main/java/chopchop/logic/commands/StatsRecipeMostMadeCommand.java
  src/main/java/chopchop/logic/parser/commands/StatsCommandParser.java
Labels: documentation

#175 Update ug ui
  docs/UserGuide.md
  docs/images/ug/UI_description.PNG
  docs/images/ug/view_recipe_1.png
Labels: documentation

#182 Add predicate tests
  src/test/java/chopchop/model/attributes/ExpiryDateMatchesKeywordsPredicateTest.java
  src/test/java/chopchop/model/attributes/IngredientsContainKeywordsPredicateTest.java
  src/test/java/chopchop/model/attributes/TagsContainKeywordsPredicateTest.java
  src/test/java/chopchop/testutil/IngredientBuilder.java
Labels: tests

#179 Update UG filter feature
  docs/UserGuide.md
  docs/images/ug/filter_ingredient_1.png
  docs/images/ug/filter_ingredient_2.png
  docs/images/ug/filter_recipe_1.png
  docs/images/ug/filter_recipe_2.png
Labels: documentation

#194 Update the UG
  docs/UserGuide.md
  docs/assets/css/style.scss
  docs/images/ug/help_message.png
  docs/images/ug/help_message_1.png
  docs/images/ug/help_message_2.png
  docs/images/ug/list_ingredient.png
  docs/images/ug/list_recipe.png
Labels: documentation

#189 Add tests for view command
  src/main/java/chopchop/logic/commands/ViewCommand.java
  src/test/java/chopchop/logic/commands/ViewCommandTest.java
Labels: tests

#188 Remove error-prone Quantity::getValue(), and increase codecov
  src/main/java/chopchop/logic/commands/FilterIngredientCommand.java
  src/main/java/chopchop/logic/commands/FilterRecipeCommand.java
  src/main/java/chopchop/model/attributes/Quantity.java
  src/main/java/chopchop/model/attributes/units/Count.java
  src/main/java/chopchop/model/attributes/units/Mass.java
  src/main/java/chopchop/model/attributes/units/Volume.java
  src/main/java/chopchop/model/ingredient/Ingredient.java
  src/test/java/chopchop/logic/parser/CommandParserTest.java
  src/test/java/chopchop/model/attributes/QuantityTest.java
Labels: tests

#195 test pr
  src/main/java/chopchop/MainApp.java
  src/main/java/chopchop/commons/core/Version.java
  src/main/java/chopchop/logic/parser/ArgName.java
  src/main/java/chopchop/logic/parser/ItemReference.java
  src/main/java/chopchop/logic/parser/commands/AddCommandParser.java
  src/main/java/chopchop/logic/parser/commands/CommonParser.java
  src/main/java/chopchop/logic/parser/commands/DeleteCommandParser.java
  src/main/java/chopchop/logic/parser/commands/EditCommandParser.java
  src/main/java/chopchop/logic/parser/commands/FilterCommandParser.java
  src/main/java/chopchop/logic/parser/commands/FindCommandParser.java
  src/main/java/chopchop/logic/parser/commands/HelpCommandParser.java
  src/main/java/chopchop/logic/parser/commands/ListCommandParser.java
  src/main/java/chopchop/logic/parser/commands/MakeCommandParser.java
  src/main/java/chopchop/logic/parser/commands/StatsCommandParser.java
  src/main/java/chopchop/logic/parser/commands/ViewCommandParser.java
  src/test/java/chopchop/logic/edit/EditDescriptorTest.java
  src/test/java/chopchop/logic/parser/ArgNameTest.java
  src/test/java/chopchop/logic/parser/CommandParserTest.java
  src/test/java/chopchop/logic/parser/ItemReferenceTest.java
  src/test/java/chopchop/logic/parser/commands/AddCommandParserTest.java
  src/test/java/chopchop/logic/parser/commands/DeleteCommandParserTest.java
  src/test/java/chopchop/logic/parser/commands/EditCommandParserTest.java
Labels: tests

#178 Add missing tests for GUI
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/chopchop/ui/CommandBox.java
  src/main/java/chopchop/ui/IngredientCard.java
  src/main/java/chopchop/ui/RecipeCard.java
  src/main/resources/view/IngredientCard.fxml
  src/main/resources/view/RecipeCard.fxml
  src/test/java/chopchop/ui/CommandBoxTest.java
  src/test/java/chopchop/ui/CommandOutputTest.java
  src/test/java/chopchop/ui/GuiUnitTest.java
  src/test/java/chopchop/ui/RecipeDisplayTest.java
  src/test/java/chopchop/ui/testutil/GuiTestAssert.java
  src/test/java/chopchop/ui/testutil/GuiTestUtil.java
  src/test/java/chopchop/ui/testutil/StageExtension.java
  src/test/java/chopchop/ui/testutil/UiPartExtension.java
  src/test/java/guitests/GuiRobot.java
  src/test/java/guitests/guihandles/CommandBoxHandle.java
  src/test/java/guitests/guihandles/CommandOutputHandle.java
  src/test/java/guitests/guihandles/DisplayPanelHandle.java
  src/test/java/guitests/guihandles/HelpWindowHandle.java
  src/test/java/guitests/guihandles/IngredientCardHandle.java
  src/test/java/guitests/guihandles/IngredientViewPanelHandle.java
  src/test/java/guitests/guihandles/MainMenuHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/NodeHandle.java
  src/test/java/guitests/guihandles/NotificationWindowHandle.java
  src/test/java/guitests/guihandles/RecipeCardHandle.java
  src/test/java/guitests/guihandles/RecipeDisplayHandle.java
  src/test/java/guitests/guihandles/RecipeViewPanelHandle.java
  src/test/java/guitests/guihandles/StageHandle.java
  src/test/java/guitests/guihandles/StatsBoxHandle.java
  src/test/java/guitests/guihandles/TextDisplayHandle.java
  src/test/java/guitests/guihandles/exceptions/NodeNotFoundException.java
  src/test/java/guitests/guihandles/exceptions/StageNotFoundException.java
Labels: tests

#108 Add undo/redo implementation details to DG
  docs/DeveloperGuide.md
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/CommitActivityDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
Labels: documentation
